Fatal error: exception Exceptions.TypeError("Error: Return statement is outside of a function")
